-- Drop and recreate the schema
drop schema public cascade;
create schema public;

-- Create tables
CREATE TABLE customers (
                           id integer GENERATED BY DEFAULT AS IDENTITY,
                           name character varying(255) NOT NULL,
                           address character varying(255) NOT NULL,
                           phone character varying(50) NOT NULL,
                           email character varying(255) NOT NULL,
                           CONSTRAINT customers_pkey PRIMARY KEY (id)
);

CREATE TABLE paper (
                       id integer GENERATED BY DEFAULT AS IDENTITY,
                       name character varying(255) NOT NULL,
                       discontinued boolean NOT NULL DEFAULT FALSE,
                       stock integer NOT NULL DEFAULT 0,
                       price double precision NOT NULL,
                       CONSTRAINT paper_pkey PRIMARY KEY (id)
);

CREATE TABLE traits (
                        id integer GENERATED BY DEFAULT AS IDENTITY,
                        trait_name character varying(255) NOT NULL,
                        CONSTRAINT traits_pkey PRIMARY KEY (id)
);

CREATE TABLE orders (
                        id integer GENERATED BY DEFAULT AS IDENTITY,
                        order_date timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
                        delivery_date date NOT NULL,
                        status character varying(50) NOT NULL DEFAULT 'pending',
                        total_amount double precision NOT NULL,
                        customer_id integer NOT NULL,
                        CONSTRAINT orders_pkey PRIMARY KEY (id),
                        CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES customers (id) ON DELETE CASCADE
);

CREATE TABLE paper_traits (
                              paper_id integer NOT NULL,
                              trait_id integer NOT NULL,
                              CONSTRAINT paper_traits_pkey PRIMARY KEY (paper_id, trait_id),
                              CONSTRAINT paper_traits_paper_id_fkey FOREIGN KEY (paper_id) REFERENCES paper (id) ON DELETE CASCADE,
                              CONSTRAINT paper_traits_trait_id_fkey FOREIGN KEY (trait_id) REFERENCES traits (id)
);

CREATE TABLE order_entries (
                               id integer GENERATED BY DEFAULT AS IDENTITY,
                               quantity integer NOT NULL,
                               product_id integer NOT NULL,
                               order_id integer NOT NULL,
                               CONSTRAINT order_entries_pkey PRIMARY KEY (id),
                               CONSTRAINT order_entries_order_id_fkey FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
                               CONSTRAINT order_entries_product_id_fkey FOREIGN KEY (product_id) REFERENCES paper (id) ON DELETE CASCADE
);

-- Create indexes
CREATE UNIQUE INDEX customers_email_key ON customers (email);
CREATE INDEX "IX_order_entries_order_id" ON order_entries (order_id);
CREATE INDEX "IX_order_entries_product_id" ON order_entries (product_id);
CREATE INDEX "IX_orders_customer_id" ON orders (customer_id);
CREATE UNIQUE INDEX unique_product_name ON paper (name);
CREATE INDEX "IX_paper_traits_trait_id" ON paper_traits (trait_id);