### Create a new customer
POST http://localhost:5139/api/customer
Content-Type: application/json

{
  "name": "John Doe",
  "address": "123 Main St",
  "phone": "123-456-7890",
  "email": "john.doe@example.com"
}

### Get all customers
GET http://localhost:5139/api/customer

### Get orders from a customer by ID
GET http://localhost:5139/api/customer/1/orders

### Get customer ID by email
GET http://localhost:5139/api/customer/email/john.doe@example.com

### Get customer by ID
GET http://localhost:5139/api/customer/1