### Create a new paper
POST http://localhost:5139/api/Paper
Content-Type: application/json

{
  "name": "lorte paper",
  "discontinued": true,
  "stock": 200,
  "price": 10.20
}

### Update an existing paper
PUT http://localhost:5139/api/Paper/4
Content-Type: application/json

{
  "id": 4,
  "name": "Updated Paper",
  "discontinued": false,
  "price": 12.0,
  "stock": 150
}

### Delete a paper
DELETE http://localhost:5139/api/Paper/4


### Add trait to paper
POST http://localhost:5139/api/Paper/6/traits
Content-Type: application/json

{
  "paperId": 6,
  "traitsIds": [
    2
  ]
}